config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    books = Book.all
    @want_to_read_books = books.where(status: 'Want to Read')
    @reading_books = books.where(status: 'Reading')
    @read_books = books.where(status: 'Read')
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def new 
    @book = Book.new
  end

  def create
    Book.create(book_params)
    redirect_to books_path
  end

  def book_params
    params.require(:book).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<div class="columns" style="padding-top: 20px">
  <div class="column">
    <h1 class="has-text-centered is-size-4">Want to read</h1>
    <% @want_to_read_books.each do |book| %>
      <div class="card" style="margin-top: 10px">
        <div class="card-image">
          <figure class="image" style="height: 250px; width: 150px; margin-left: auto; margin-right: auto">
            <%= link_to image_tag(book.image_url), book_path(book) %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src=<%= book.author_image_url %> alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= book.title %></p>
              <p class="subtitle is-6"><%= book.author %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="column">
    <h1 class="has-text-centered is-size-4">Reading</h1>
    <% @reading_books.each do |book| %>
      <div class="card" style="margin-top: 10px">
        <div class="card-image">
          <figure class="image" style="height: 250px; width: 150px; margin-left: auto; margin-right: auto">
            <%= link_to image_tag(book.image_url), book_path(book) %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src=<%= book.author_image_url %> alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= book.title %></p>
              <p class="subtitle is-6"><%= book.author %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="column">
    <h1 class="has-text-centered is-size-4">Read</h1>
    <% @read_books.each do |book| %>
      <div class="card" style="margin-top: 10px">
        <div class="card-image">
          <figure class="image" style="height: 250px; width: 150px; margin-left: auto; margin-right: auto">
            <%= link_to image_tag(book.image_url), book_path(book) %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src=<%= book.author_image_url %> alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= book.title %></p>
              <p class="subtitle is-6"><%= book.author %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div style="margin-top: 10px">
  <h1 class="title is-4">Add a new book</h1>

  <%= form_with(model: @book, local: true) do |form| %>
    <div class="columns">
      <div class="field column">
        <%= form.text_field :title, class: "control input is-danger", placeholder: 'Title' %>
      </div>
      <div class="field column">
        <%= form.text_field :author, class: "control input is-danger", placeholder: 'Author' %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= form.text_area :description, class: "textarea is-danger", placeholder: 'Description', rows: 4 %>
      </div>
      <div class="column">
        <div class="columns">
          <div class="column is-half">
            <div class="select is-danger" style="width: 100%">
              <%= form.select :status, ['Status', 'Want to Read', 'Reading', 'Read'], {}, { style: 'width: 100%' } %>
            </div>
          </div>
          <div class="field column is-half">
            <%= form.text_field :year, class: "control input is-danger", placeholder: 'Year' %>
          </div>
        </div>
        <div class="columns">
          <div class="field column">
            <%= form.text_field :image_url, class: "control input is-danger", placeholder: 'Book Image URL' %>
          </div>
          <div class="field column">
            <%= form.text_field :author_image_url, class: "control input is-danger", placeholder: 'Author Image URL' %>
          </div>
        </div>
      </div>
    </div>
    <%= form.submit 'Save Book', class: 'button is-warning' %>
  <% end %>
</div>

app/views/books/show.html.erb
<h1 class="is-size-3"><%= @book.title %> - (<%= @book.year %>)</h1>
<div class="columns">
  <div class="column">
    <h1 class="is-size-5"><%= @book.author %> </h1>
    <h1 class="is-size-6"><%= @book.description %> </h1>
  </div>
  <div class="column has-text-centered">
    <%= image_tag(@book.image_url, style: 'height: 170px;') %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <section class="hero is-medium is-danger is-bold">
        <div class="hero-head">
          <nav class="navbar">
            <div class="container">
              <div id="navbarMenuHeroA" class="navbar-menu">
                <div class="navbar-start">
                  <span class="navbar-item">
                    <%= link_to 'Add new book', new_book_path, class: 'button is-danger is-inverted' %>
                  </span>
                </div>
              </div>
            </div>
          </nav>
        </div>
        <div class="hero-body">
          <div class="container">
            <h1>
              <%= link_to 'Book manager', books_path, class: 'title is-1' %>
            </h1>
            <h2 class="subtitle">
              Be organized
            </h2>
          </div>
        </div>
      </section>
      <%= yield %>
    </div>
  </body>
</html>